ruby: Fix warnings about unused variables (NFC)
clang throws the following warnings:

../ruby/action.cc:76:38: error: unused variable 'ActionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *ActionClassName = "InfoAction";
                                     ^
../ruby/action.cc:92:38: error: unused variable 'ActionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *ActionClassName = "ConfigAction";
                                     ^
../ruby/action.cc:108:38: error: unused variable 'ActionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *ActionClassName = "FetchAction";
                                     ^
../ruby/action.cc:124:38: error: unused variable 'ActionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *ActionClassName = "InstallAction";
                                     ^
../ruby/action.cc:140:38: error: unused variable 'ActionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *ActionClassName = "PretendAction";
                                     ^
../ruby/action.cc:156:38: error: unused variable 'OptionClassName' [-Werror,-Wunused-const-variable]
        static constexpr const char *OptionClassName = "UninstallAction";
                                     ^
6 errors generated.