build: libpaludispaludisenvironment depends on libpaludis_SE
In file included from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/environment.hh:25,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/environments/paludis/keywords_conf.cc:21:
/var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/output_manager-fwd.hh:29:10: fatal error: paludis/output_manager-se.hh: No such file or directory
   29 | #include <paludis/output_manager-se.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [paludis/environments/paludis/CMakeFiles/libpaludispaludisenvironment.dir/build.make:111: paludis/environments/paludis/CMakeFiles/libpaludispaludisenvironment.dir/keywords_conf.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8427: paludis/environments/paludis/CMakeFiles/libpaludispaludisenvironment.dir/all] Error 2
make: *** [Makefile:185: all] Error 2