resolver: job_requirements: Make compare operator const
Fixes the following error:
```
paludis/resolver/job_requirements.cc:84:32:   required from here
/usr/x86_64-pc-linux-gnu/include/c++/12.2.0/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/x86_64-pc-linux-gnu/include/c++/12.2.0/bits/stl_tree.h:770:15: note: 'std::is_invocable_v<const paludis::resolver::JobRequirementComparator&, const paludis::resolver::JobRequirement&, const paludis::resolver::JobRequirement&>' evaluates to false
```