Fix assorted build failures with clang
    ../../../paludis/paludis/util/sequence-impl.hh:162:21: error: expected expression
        _imp->list.sort<const C_ &>(c);
- just a missing "template"

    ../../paludis/paludis/util/visitor.hh:322:24: error: no viable overloaded '='
                    result = _unwrapped_visitor.visit(t);
    [snip]
    ../../paludis/paludis/mask.cc:43:17: note: in instantiation of function template specialization 'paludis::DeclareAbstractAcceptMethods<paludis::Mask,
          paludis::TypeListEntry<paludis::UserMask, paludis::TypeListEntry<paludis::UnacceptedMask, paludis::TypeListEntry<paludis::RepositoryMask,
          paludis::TypeListEntry<paludis::UnsupportedMask, paludis::TypeListTail> > > > >::make_accept_returning<<lambda at
          ../../paludis/paludis/mask.cc:44:9>, <lambda at ../../paludis/paludis/mask.cc:45:9>, <lambda at ../../paludis/paludis/mask.cc:46:9>, <lambda at
          ../../paludis/paludis/mask.cc:47:9> >' requested here
        return mask.make_accept_returning(
    /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/basic_string.h:543:7: note: candidate function not viable: 'this' argument has type
          'const std::basic_string<char>', but method is not marked const
          operator=(const basic_string& __str)
    [snip]
- template argument inferred as const and then used for temporary
  variable that gets assigned, so needs to be forced non-const

    In file included from ../../../../paludis/paludis/repositories/e/e_choice_value.cc:24:
    ../../../../paludis/paludis/util/pool-impl.hh:171:23: error: call to function 'operator==' that is neither visible in the template definition nor
          found by argument-dependent lookup
            return _value == static_cast<const ConcretePoolKey<T_> &>(other)._value;
    [snip]
    ../../../../paludis/paludis/repositories/e/e_choice_value.cc:147:10: note: 'operator==' should be declared prior to the call site or in namespace
          'paludis::erepository'
        bool operator== (const EChoiceValueParams & a, const EChoiceValueParams & b)
- see http://clang.llvm.org/compatibility.html#dep_lookup

    /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/functional:1925:2: error: no matching function for call to object of type
          'std::_Bind<std::_Mem_fn<void (paludis::resolver::Decider::*)(const std::shared_ptr<const paludis::resolver::Resolution> &, const
          std::shared_ptr<const paludis::resolver::Constraint> &, const std::shared_ptr<const paludis::resolver::Decision> &) __attribute__((noreturn))
          const> (paludis::resolver::Decider *, std::shared_ptr<paludis::resolver::Resolution>, std::shared_ptr<const paludis::resolver::Constraint>,
          std::shared_ptr<paludis::resolver::Decision>)>'
            (*_Base::_M_get_pointer(__functor))(
    [snip]
    ../../../paludis/paludis/resolver/decider.cc:936:65: note: in instantiation of function template specialization 'std::function<void
          ()>::function<std::_Bind<std::_Mem_fn<void (paludis::resolver::Decider::*)(const std::shared_ptr<const paludis::resolver::Resolution> &, const
          std::shared_ptr<const paludis::resolver::Constraint> &, const std::shared_ptr<const paludis::resolver::Decision> &) __attribute__((noreturn))
          const> (paludis::resolver::Decider *, std::shared_ptr<paludis::resolver::Resolution>, std::shared_ptr<const paludis::resolver::Constraint>,
          std::shared_ptr<paludis::resolver::Decision>)> >' requested here
                resolution->decision()->accept(WrongDecisionVisitor(std::bind(
    /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/functional:1211:2: note: candidate template ignored: substitution failure [with _Args = <>]: no
          matching function for call to object of type 'std::_Mem_fn<void (paludis::resolver::Decider::*)(const std::shared_ptr<const
          paludis::resolver::Resolution> &, const std::shared_ptr<const paludis::resolver::Constraint> &, const std::shared_ptr<const
          paludis::resolver::Decision> &) __attribute__((noreturn)) const>'
            operator()(_Args&&... __args)
    [snip]
- not sure why it doesn't like this, but its nicer with the anonymous
  function anyway

    ../../paludis/python/dep_spec.cc:1409:16: error: explicit instantiation of 'paludis::WrappedForwardIterator' must occur in namespace 'paludis'
    template class WrappedForwardIterator<PythonCompositeDepSpec::ConstIteratorTag,
    ../../paludis/python/exception.cc:32:16: error: explicit instantiation of 'paludis::Singleton' must occur in namespace 'paludis'
    template class Singleton<ExceptionRegister>;
    ../../paludis/ruby/paludis_ruby.cc:38:16: error: explicit instantiation of 'paludis::Singleton' must occur in namespace 'paludis'
    template class Singleton<RegisterRubyClass>;
- self-explanatory