Fix clang warnings about wrong dtor names (NFC)
clang throws the following warnings:

> In file included from /home/marv/devel/paludis-worktrees/werror/paludis/util/set.cc:20:
> In file included from /home/marv/devel/paludis-worktrees/werror/paludis/util/set-impl.hh:24:
> /home/marv/devel/paludis-worktrees/werror/paludis/util/pimp-impl.hh:47:18: error: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [-Werror,-Wdtor-name]
> paludis::Pimp<C_>::~Pimp()
> ~~~~~~~~~~~~~~~~~^~
>                  ::Pimp
> In file included from /home/marv/devel/paludis-worktrees/werror/paludis/util/set.cc:20:
> /home/marv/devel/paludis-worktrees/werror/paludis/util/set-impl.hh:84:21: error: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [-Werror,-Wdtor-name]
> paludis::Set<T_, C_>::~Set() = default;
> ~~~~~~~~~~~~~~~~~~~~^~
>                     ::Set
> 2 errors generated.

Quoting the explanation from Richard Smith[1] he gave in the upstream bug:

> The diagnostic is correct, per the standard rules as written; strictly-speaking, the C++ rules require this destructor to be written as
>
> template<typename T>
> A::B<T>::~B<T>()
>
> Per C++ [basic.lookup.qual]p6:
>
> """
> In a qualified-id of the form:
>
> nested-name-specifier[opt] type-name :: ~ type-name
>
> the second type-name is looked up in the same scope as the first.
> """
>
> This means that the second B is looked up in class A, which finds only the class template B and not the injected-class-name.
>
> This is not an especially useful rule, and likely isn't the intended rule,
> which is why this diagnostic (along with a bunch of similar diagnostics for
> plausible but formally incorrect destructor names) is disabled by default but
> included in -pedantic.

Therefore this patch adds the template arguments to the destructor name in
order to fix the warnings

[1] https://bugs.llvm.org/show_bug.cgi?id=46979#c1