thread_pool: Remove 'noexcept' from std::function<> template argument
Starting with C++17 the `noexcept` specifier is part of the type,
therefore `void ()` and `void () noexcept` are no longer the same type.

libstdc++ and libc++ refuse to compile `std::function<void () noexcept>`
in C++17 mode because it's undefined:
```
src/clients/cave/cmd_generate_metadata.cc:315:32: error: implicit instantiation of undefined template 'std::function<void () noexcept>'
            pool.create_thread(std::bind(&worker, std::ref(mutex), std::ref(i), std::cref(i_end), std::ref(fail), std::ref(callback)));
                               ^
/usr/include/c++/v1/__functional/function.h:76:82: note: template is declared here
template<class _Fp> class _LIBCPP_DEPRECATED_CXX03_FUNCTION _LIBCPP_TEMPLATE_VIS function; // undefined
                                                                                 ^
paludis/util/thread_pool.hh:62:71: note: passing argument to parameter here
            void create_thread(const std::function<void () noexcept> &);
                                                                      ^
1 error generated.
```

Remove the `noexcept` to make it compile with C++17