build: Resolver tests use fake installed repository
I encountered the following build error trying to build an Exherbo musl stage:

make[2]: Leaving directory '/var/tmp/paludis/build/sys-apps-paludis-scm/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/sys-apps-paludis-scm/work/build'
In file included from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/repository.hh:39,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/repositories/fake/fake_repository_base.hh:23,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/repositories/fake/fake_installed_repository.hh:23,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/resolver/resolver_test.hh:64,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/resolver/resolver_test.cc:20:
/var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/output_manager-fwd.hh:29:10: fatal error: paludis/output_manager-se.hh: No such file or directory
   29 | #include <paludis/output_manager-se.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [paludis/resolver/CMakeFiles/libpaludisresolvertest.dir/build.make:85: paludis/resolver/CMakeFiles/libpaludisresolvertest.dir/resolver_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8980: paludis/resolver/CMakeFiles/libpaludisresolvertest.dir/all] Error 2
make: *** [Makefile:185: all] Error 2

fake_installed_repository.hh is used by resolver_test.{cc,hh} but there's no dependency for it
specified (libpaludisresolvertest is built statically so it just needs the headers to be available).
Add a dependency on libpaludisfakerepository which in turn depends on libpaludis{,util}_SE