build: repositories depend on libpaludis_SE
In file included from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/package_id.hh:38,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/repositories/unpackaged/unpackaged_id.hh:23,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/repositories/unpackaged/unpackaged_id.cc:20:
/var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/metadata_key-fwd.hh:43:10: fatal error: paludis/metadata_key-se.hh: No such file or directory
   43 | #include <paludis/metadata_key-se.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [paludis/repositories/unpackaged/CMakeFiles/libpaludisunpackagedrepository.dir/build.make:98: paludis/repositories/unpackaged/CMakeFiles/libpaludisunpackage
drepository.dir/unpackaged_id.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8127: paludis/repositories/unpackaged/CMakeFiles/libpaludisunpackagedrepository.dir/all] Error 2
make: *** [Makefile:185: all] Error 2