python: Disable -Wunused-result for tests
python/additional_tests.cc: In function 'void environment::test_env(paludis::Environment&)':
python/additional_tests.cc:59:36: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   59 |         e.mask_for_user(pid, false);
      |                                    ^
python/additional_tests.cc:63:25: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   63 |         e.bashrc_files();
      |                         ^
python/additional_tests.cc:65:25: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   65 |         e.syncers_dirs();
      |                         ^
python/additional_tests.cc:67:26: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   67 |         e.fetchers_dirs();
      |                          ^
python/additional_tests.cc:69:22: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   69 |         e.hook_dirs();
      |                      ^
python/additional_tests.cc:75:28: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   75 |         e.mirrors("mirror");
      |                            ^
python/additional_tests.cc:77:22: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   77 |         e.set_names();
      |                      ^
python/additional_tests.cc:79:30: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   79 |         e.set(SetName("set"));
      |                              ^
python/additional_tests.cc:81:46: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   81 |         e.perform_hook(Hook("test"), nullptr);
      |                                              ^
python/additional_tests.cc:83:25: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
   83 |         e.distribution();
      |                         ^
python/additional_tests.cc:85:27: error: ignoring return value of 'paludis::MetadataKeyHolder::MetadataConstIterator paludis::MetadataKeyHolder::begin_metadata() const', declared with attribute 'warn_unused_result' [-Werror=unused-result]
   85 |         e.begin_metadata();
      |                           ^
In file included from paludis/environment.hh:34,
                 from python/additional_tests.cc:28:
paludis/metadata_key_holder.hh:72:35: note: declared here
   72 |             MetadataConstIterator begin_metadata() const PALUDIS_ATTRIBUTE((warn_unused_result));
      |                                   ^~~~~~~~~~~~~~
python/additional_tests.cc: In function 'void metadata_key::test_metadata_key(const paludis::MetadataKey&)':
python/additional_tests.cc:124:21: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  124 |         m.raw_name();
      |                     ^
python/additional_tests.cc:125:23: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  125 |         m.human_name();
      |                       ^
python/additional_tests.cc:126:25: error: unused variable 'foo' [-Werror=unused-variable]
  126 |         MetadataKeyType foo(m.type());
      |                         ^~~
python/additional_tests.cc: In function 'void metadata_key::test_metadata_package_id_key(const paludis::MetadataValueKey<std::shared_ptr<const paludis::PackageID> >&)':
python/additional_tests.cc:132:24: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  132 |         m.parse_value();
      |                        ^
python/additional_tests.cc: In function 'void metadata_key::test_metadata_string_key(const paludis::MetadataValueKey<std::__cxx11::basic_string<char> >&)':
python/additional_tests.cc:138:24: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  138 |         m.parse_value();
      |                        ^
python/additional_tests.cc: In function 'void metadata_key::test_metadata_choices_key(const paludis::MetadataValueKey<std::shared_ptr<const paludis::Choices> >&)':
python/additional_tests.cc:157:24: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  157 |         m.parse_value();
      |                        ^
python/additional_tests.cc: In function 'void metadata_key::test_metadata_spec_tree_key(const paludis::MetadataSpecTreeKey<C_>&) [with C_ = paludis::SpecTree<paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::FetchableURIDepSpec>, paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::LabelsDepSpec<paludis::URILabel> >, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AllDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::ConditionalDepSpec>, paludis::TypeListTail> > > >, paludis::AllDepSpec>]':
python/additional_tests.cc:178:24: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  178 |         m.parse_value();
      |                        ^
python/additional_tests.cc:179:26: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  179 |         m.initial_label();
      |                          ^
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_set_key(const paludis::MetadataCollectionKey<C_>&) [with C_ = paludis::Set<paludis::WrappedValue<paludis::KeywordNameTag> >]':
python/additional_tests.cc:205:12:   required from here
python/additional_tests.cc:164:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  164 |         m.parse_value();
      |         ^
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_set_key(const paludis::MetadataCollectionKey<C_>&) [with C_ = paludis::Set<std::__cxx11::basic_string<char> >]':
python/additional_tests.cc:206:12:   required from here
python/additional_tests.cc:164:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_spec_tree_key(const paludis::MetadataSpecTreeKey<C_>&) [with C_ = paludis::SpecTree<paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::LicenseDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AllDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AnyDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::ConditionalDepSpec>, paludis::TypeListTail> > > >, paludis::AllDepSpec>]':
python/additional_tests.cc:207:12:   required from here
python/additional_tests.cc:171:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
  171 |         m.parse_value();
      |         ^
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_spec_tree_key(const paludis::MetadataSpecTreeKey<C_>&) [with C_ = paludis::SpecTree<paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::PackageDepSpec>, paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::BlockDepSpec>, paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::LabelsDepSpec<paludis::DependenciesLabel> >, paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::NamedSetDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AllDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AnyDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::ConditionalDepSpec>, paludis::TypeListTail> > > > > > >, paludis::AllDepSpec>]':
python/additional_tests.cc:208:12:   required from here
python/additional_tests.cc:171:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_spec_tree_key(const paludis::MetadataSpecTreeKey<C_>&) [with C_ = paludis::SpecTree<paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::PlainTextDepSpec>, paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::PlainTextLabelDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AllDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::ConditionalDepSpec>, paludis::TypeListTail> > > >, paludis::AllDepSpec>]':
python/additional_tests.cc:209:12:   required from here
python/additional_tests.cc:171:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
python/additional_tests.cc: In instantiation of 'void metadata_key::test_metadata_spec_tree_key(const paludis::MetadataSpecTreeKey<C_>&) [with C_ = paludis::SpecTree<paludis::TypeListEntry<paludis::SpecTreeLeafNodeType<paludis::SimpleURIDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::AllDepSpec>, paludis::TypeListEntry<paludis::SpecTreeInnerNodeType<paludis::ConditionalDepSpec>, paludis::TypeListTail> > >, paludis::AllDepSpec>]':
python/additional_tests.cc:211:12:   required from here
python/additional_tests.cc:171:9: error: ignoring return value of function declared with attribute 'warn_unused_result' [-Werror=unused-result]
cc1plus: all warnings being treated as errors
[166/464] Building CXX object src/clients/cave/CMakeFiles/libcave.dir/command_factory.cc.o
ninja: build stopped: subcommand failed.