build: libpaludisresolver depends on libpaludis_SE
$ ninja -j1 libpaludisresolver
[30/104] Building CXX object paludis/resolver/CMakeFiles/libpaludisresolver.dir/accumulate_deps.cc.o
FAILED: paludis/resolver/CMakeFiles/libpaludisresolver.dir/accumulate_deps.cc.o
/usr/x86_64-pc-linux-gnu/bin/g++ -DDATADIR=\"/usr/share\" -DENABLE_PBINS -DENABLE_PYTHON_HOOKS -DENABLE_STRIPPER -DLIBDIR=\"/usr/x86_64-pc-linux-gnu/lib\" -DLIBEXECDIR=\"/usr/x86_64-pc-linux-gnu/libexec\" -DPALUDIS_NO_EXPLICIT_FULLY_SPECIALISED=1 -DPALUDIS_VERSION_MAJOR=3 -DPALUDIS_VERSION_MINOR=0 -DSYSCONFDIR=\"/etc\" -I. -I../ -pipe -O0 -pedantic -g3 -Wall -Wextra -Wold-style-cast -Wredundant-decls -Wstrict-null-sentinel -Wmissing-noreturn -Woverloaded-virtual -Winit-self -Wunreachable-code -Wunused -Wshadow -Wwrite-strings -Wfloat-equal -Wno-ignored-qualifiers -Wno-non-virtual-dtor -fvisibility=hidden -fvisibility-inlines-hidden -g -fPIC -std=gnu++11 -MD -MT paludis/resolver/CMakeFiles/libpaludisresolver.dir/accumulate_deps.cc.o -MF paludis/resolver/CMakeFiles/libpaludisresolver.dir/accumulate_deps.cc.o.d -o paludis/resolver/CMakeFiles/libpaludisresolver.dir/accumulate_deps.cc.o -c ../paludis/resolver/accumulate_deps.cc
In file included from ../paludis/resolver/accumulate_deps-fwd.hh:25,
                 from ../paludis/resolver/accumulate_deps.hh:23,
                 from ../paludis/resolver/accumulate_deps.cc:23:
../paludis/package_id-fwd.hh:59:10: fatal error: paludis/package_id-se.hh: No such file or directory
   59 | #include <paludis/package_id-se.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.