build: Disable -Wreturn-type-c-linkage warning
There are two locations that trigger this warning:

> In file included from paludis/repositories/accounts/accounts_repository.cc:39:
> paludis/hook.hh:161:48: error: 'paludis_hook_run_3' has C-linkage specified, but returns user-defined type 'paludis::HookResult' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
> extern "C" paludis::HookResult PALUDIS_VISIBLE paludis_hook_run_3(
>                                                ^
> paludis/hook.hh:167:89: error: 'paludis_hook_auto_phases' has C-linkage specified, but returns incomplete type 'const std::shared_ptr<const paludis::Sequence<std::string>>' (aka 'const shared_ptr<const Sequence<basic_string<char>>>') which could be incompatible with C [-Werror,-Wreturn-type-c-linkage]
> extern "C" const std::shared_ptr<const paludis::Sequence<std::string> > PALUDIS_VISIBLE paludis_hook_auto_phases(
>                                                                                         ^
> 2 errors generated.

Since we want C mangling for the function name but use a C++ return type at the
same time we can't fix the warning properly unfortunately. Disable it so it doesn't
prevent us from having a warning-free build