build: libcave depends on libpaludis{,util}_SE
[  3%] Building CXX object src/clients/cave/CMakeFiles/libcave.dir/colour_pretty_printer.cc.o
In file included from /home/marv/devel/paludis/paludis/pretty_printer.hh:25:0,
                 from /home/marv/devel/paludis/paludis/formatted_pretty_printer.hh:25,
                 from /home/marv/devel/paludis/src/clients/cave/colour_pretty_printer.hh:23,
                 from /home/marv/devel/paludis/src/clients/cave/colour_pretty_printer.cc:20:
/home/marv/devel/paludis/paludis/util/fs_path-fwd.hh:48:38: fatal error: paludis/util/fs_path-se.hh: No such file or directory
compilation terminated.
make[7]: *** [src/clients/cave/CMakeFiles/libcave.dir/build.make:63: src/clients/cave/CMakeFiles/libcave.dir/colour_pretty_printer.cc.o] Error 1

[  6%] Building CXX object src/clients/cave/CMakeFiles/libcave.dir/colour_pretty_printer.cc.o
In file included from /home/marv/devel/paludis/paludis/pretty_printer.hh:27:0,
                 from /home/marv/devel/paludis/paludis/formatted_pretty_printer.hh:25,
                 from /home/marv/devel/paludis/src/clients/cave/colour_pretty_printer.hh:23,
                 from /home/marv/devel/paludis/src/clients/cave/colour_pretty_printer.cc:20:
/home/marv/devel/paludis/paludis/package_id-fwd.hh:59:36: fatal error: paludis/package_id-se.hh: No such file or directory