build: examples depend on libpaludis_SE
In file included from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/metadata_key_holder.hh:26,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/about_metadata.hh:27,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/build/paludis/paludis.hh:44,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/doc/api/cplusplus/examples/example_command_line.hh:8,
                 from /var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/doc/api/cplusplus/examples/example_command_line.cc:8:
/var/tmp/paludis/build/sys-apps-paludis-scm/work/paludis-scm/paludis/metadata_key-fwd.hh:43:10: fatal error: paludis/metadata_key-se.hh: No such file or directory
   43 | #include <paludis/metadata_key-se.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [doc/api/cplusplus/examples/CMakeFiles/libpaludisexamples.dir/build.make:85: doc/api/cplusplus/examples/CMakeFiles/libpaludisexamples.dir/example_command_line.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:12313: doc/api/cplusplus/examples/CMakeFiles/libpaludisexamples.dir/all] Error 2