util: iterator_range: Provide const_iterator definition
Fixes the following build error with gtest 1.11.0:
```
FAILED: paludis/util/CMakeFiles/iterator_range_TEST.dir/iterator_range_TEST.cc.o
/usr/bin/g++ -DDATADIR=\"/usr/share\" -DENABLE_PBINS -DENABLE_PYTHON_HOOKS -DENABLE_STRIPPER -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DLIBDIR=\"/usr/x86_64-pc-linux-gnu/lib\" -DLIBEXECDIR=\"/usr/x86_64-pc-linux-gnu/libexec\" -DPALUDIS_NO_EXPLICIT_FULLY_SPECIALISED=1 -DPALUDIS_VERSION_MAJOR=3 -DPALUDIS_VERSION_MINOR=0 -DSYSCONFDIR=\"/etc\" -I/builds/marv/paludis/build-obj -I/builds/marv/paludis -Werror -pipe -O0 -pedantic -g3 -Wall -Wextra -Wold-style-cast -Wredundant-decls -Wstrict-null-sentinel -Wmissing-noreturn -Woverloaded-virtual -Winit-self -Wunreachable-code -Wunused -Wshadow -Wwrite-strings -Wfloat-equal -Wno-ignored-qualifiers -Wno-non-virtual-dtor -fvisibility=hidden -fvisibility-inlines-hidden -Wno-return-type-c-linkage -g -fPIE -std=gnu++17 -MD -MT paludis/util/CMakeFiles/iterator_range_TEST.dir/iterator_range_TEST.cc.o -MF paludis/util/CMakeFiles/iterator_range_TEST.dir/iterator_range_TEST.cc.o.d -o paludis/util/CMakeFiles/iterator_range_TEST.dir/iterator_range_TEST.cc.o -c /builds/marv/paludis/paludis/util/iterator_range_TEST.cc
In file included from /usr/include/gmock/gmock-spec-builders.h:75,
                 from /usr/include/gmock/gmock-function-mocker.h:42,
                 from /usr/include/gmock/gmock.h:61,
                 from /builds/marv/paludis/paludis/util/iterator_range_TEST.cc:24:
/usr/include/gmock/gmock-matchers.h: In instantiation of 'bool testing::internal::ElementsAreMatcherImpl<Container>::MatchAndExplain(Container, testing::MatchResultListener*) const [with Container = const paludis::IteratorRange<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > > >&]':
/usr/include/gmock/gmock-matchers.h:3228:8:   required from here
/usr/include/gmock/gmock-matchers.h:3238:43: error: no type named 'const_iterator' in 'testing::internal::ElementsAreMatcherImpl<const paludis::IteratorRange<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > > >&>::StlContainer' {aka 'class paludis::IteratorRange<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > > >'}
 3238 |     typename StlContainer::const_iterator it = stl_container.begin();
      |                                           ^~
```

This surfaced in the Gentoo build in our CI pipeline. gtest >=1.12.0 uses
`auto` instead of `typename Container::const_iterator` which is why the error
didn't come up on Exherbo where gtest is already at 1.12.0