python: Fix warning about unused variable (NFC)
> python/additional_tests.cc:126:25: error: Value stored to 'foo' during its initialization is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
>         MetadataKeyType foo(m.type());
>                         ^